// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: resource/v1/delta.proto

package resourcev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeltaOperation is the type of change that is being made to the object.
type DeltaOperation int32

const (
	// Create a new object in the graph.
	DeltaOperation_DELTA_OPERATION_CREATE DeltaOperation = 0
	// Update an existing object in the graph.
	DeltaOperation_DELTA_OPERATION_UPDATE DeltaOperation = 1
	// Delete an object from the graph.
	DeltaOperation_DELTA_OPERATION_DELETE DeltaOperation = 2
	// Heartbeat is a special type of delta that is used to keep an object with a
	// TTL alive.
	DeltaOperation_DELTA_OPERATION_HEARTBEAT DeltaOperation = 3
)

// Enum value maps for DeltaOperation.
var (
	DeltaOperation_name = map[int32]string{
		0: "DELTA_OPERATION_CREATE",
		1: "DELTA_OPERATION_UPDATE",
		2: "DELTA_OPERATION_DELETE",
		3: "DELTA_OPERATION_HEARTBEAT",
	}
	DeltaOperation_value = map[string]int32{
		"DELTA_OPERATION_CREATE":    0,
		"DELTA_OPERATION_UPDATE":    1,
		"DELTA_OPERATION_DELETE":    2,
		"DELTA_OPERATION_HEARTBEAT": 3,
	}
)

func (x DeltaOperation) Enum() *DeltaOperation {
	p := new(DeltaOperation)
	*p = x
	return p
}

func (x DeltaOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeltaOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_resource_v1_delta_proto_enumTypes[0].Descriptor()
}

func (DeltaOperation) Type() protoreflect.EnumType {
	return &file_resource_v1_delta_proto_enumTypes[0]
}

func (x DeltaOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeltaOperation.Descriptor instead.
func (DeltaOperation) EnumDescriptor() ([]byte, []int) {
	return file_resource_v1_delta_proto_rawDescGZIP(), []int{0}
}

// Delta is a set of graph objects that is being modified by operation op.
type Delta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            DeltaOperation         `protobuf:"varint,1,opt,name=op,proto3,enum=resource.v1.DeltaOperation" json:"op,omitempty"`
	Objects       []*Object              `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delta) Reset() {
	*x = Delta{}
	mi := &file_resource_v1_delta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_delta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_resource_v1_delta_proto_rawDescGZIP(), []int{0}
}

func (x *Delta) GetOp() DeltaOperation {
	if x != nil {
		return x.Op
	}
	return DeltaOperation_DELTA_OPERATION_CREATE
}

func (x *Delta) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

// Object is a resource or relationship object that is part of the delta set.
type Object struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique object name within the delta set.
	// For DeltaType_DELTA_TYPE DELETE events, only this field needs to be set.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Time-to-live value for the object. For each object, a timer is started.
	// The timer is reset each time the object is received with a new TTL.
	// If the object is received with no TTL set, the timer is removed for the
	// object. Upon expiration of the timer, the object is considered deleted.
	//
	// The TTL can be refreshed or changed by sending a Delta containing an Object
	// with the same name that doesn't change the object version. In this case the
	// object field does not need to be populated, which allows for light-weight
	// "heartbeat" updates to keep an object with a TTL alive.
	//
	// The TTL feature is meant to support cleaning up objects in the event of
	// a systems-agent removal/failure. For example, if the Kubernetes cluster
	// where the systems agent is deployed in is spun down, then all the resources
	// from the cluster will be deleted from the graph once the TTL expires.
	Ttl *durationpb.Duration `protobuf:"bytes,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// The delta version of the Delta change set that the object is a part of.
	// It is used to keep track of the state of individual objects. The version is
	// set and maintained by the client sending Deltas.
	//
	// NOTE: the version string should only be used for comparisions!
	// It is not guaranteed that the version string is monotonically increasing.
	DeltaVersion string `protobuf:"bytes,3,opt,name=delta_version,json=deltaVersion,proto3" json:"delta_version,omitempty"`
	// The Resource or Relationship object
	Object        *anypb.Any `protobuf:"bytes,4,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_resource_v1_delta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_delta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_resource_v1_delta_proto_rawDescGZIP(), []int{1}
}

func (x *Object) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Object) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *Object) GetDeltaVersion() string {
	if x != nil {
		return x.DeltaVersion
	}
	return ""
}

func (x *Object) GetObject() *anypb.Any {
	if x != nil {
		return x.Object
	}
	return nil
}

var File_resource_v1_delta_proto protoreflect.FileDescriptor

var file_resource_v1_delta_proto_rawDesc = string([]byte{
	0x0a, 0x17, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x65,
	0x6c, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x63, 0x0a, 0x05, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x02, 0x6f, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x2d, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x9c, 0x01, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x74,
	0x74, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x5f, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x6c, 0x74, 0x61,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x06, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x2a, 0x83, 0x01, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x16, 0x44, 0x45, 0x4c, 0x54,
	0x41, 0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x43, 0x52, 0x45, 0x41,
	0x54, 0x45, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x44, 0x45, 0x4c, 0x54, 0x41, 0x5f, 0x4f, 0x50,
	0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x01,
	0x12, 0x1a, 0x0a, 0x16, 0x44, 0x45, 0x4c, 0x54, 0x41, 0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x19,
	0x44, 0x45, 0x4c, 0x54, 0x41, 0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x48, 0x45, 0x41, 0x52, 0x54, 0x42, 0x45, 0x41, 0x54, 0x10, 0x03, 0x42, 0xa2, 0x01, 0x0a, 0x0f,
	0x63, 0x6f, 0x6d, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x42,
	0x0a, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x36, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x74, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x67, 0x65, 0x6e, 0x67, 0x6f, 0x2f, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x52, 0x58, 0x58, 0xaa, 0x02, 0x0b, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0b, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x17, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x3a, 0x3a, 0x56, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_resource_v1_delta_proto_rawDescOnce sync.Once
	file_resource_v1_delta_proto_rawDescData []byte
)

func file_resource_v1_delta_proto_rawDescGZIP() []byte {
	file_resource_v1_delta_proto_rawDescOnce.Do(func() {
		file_resource_v1_delta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_v1_delta_proto_rawDesc), len(file_resource_v1_delta_proto_rawDesc)))
	})
	return file_resource_v1_delta_proto_rawDescData
}

var file_resource_v1_delta_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resource_v1_delta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resource_v1_delta_proto_goTypes = []any{
	(DeltaOperation)(0),         // 0: resource.v1.DeltaOperation
	(*Delta)(nil),               // 1: resource.v1.Delta
	(*Object)(nil),              // 2: resource.v1.Object
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
	(*anypb.Any)(nil),           // 4: google.protobuf.Any
}
var file_resource_v1_delta_proto_depIdxs = []int32{
	0, // 0: resource.v1.Delta.op:type_name -> resource.v1.DeltaOperation
	2, // 1: resource.v1.Delta.objects:type_name -> resource.v1.Object
	3, // 2: resource.v1.Object.ttl:type_name -> google.protobuf.Duration
	4, // 3: resource.v1.Object.object:type_name -> google.protobuf.Any
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_resource_v1_delta_proto_init() }
func file_resource_v1_delta_proto_init() {
	if File_resource_v1_delta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_v1_delta_proto_rawDesc), len(file_resource_v1_delta_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_v1_delta_proto_goTypes,
		DependencyIndexes: file_resource_v1_delta_proto_depIdxs,
		EnumInfos:         file_resource_v1_delta_proto_enumTypes,
		MessageInfos:      file_resource_v1_delta_proto_msgTypes,
	}.Build()
	File_resource_v1_delta_proto = out.File
	file_resource_v1_delta_proto_goTypes = nil
	file_resource_v1_delta_proto_depIdxs = nil
}
