// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package resourcev1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Namespace within kubernetes types, where deepcopy-gen is used.
func (in *Namespace) DeepCopyInto(out *Namespace) {
	p := proto.Clone(in).(*Namespace)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Namespace. Required by controller-gen.
func (in *Namespace) DeepCopy() *Namespace {
	if in == nil {
		return nil
	}
	out := new(Namespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Namespace. Required by controller-gen.
func (in *Namespace) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CloudNamespace within kubernetes types, where deepcopy-gen is used.
func (in *CloudNamespace) DeepCopyInto(out *CloudNamespace) {
	p := proto.Clone(in).(*CloudNamespace)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudNamespace. Required by controller-gen.
func (in *CloudNamespace) DeepCopy() *CloudNamespace {
	if in == nil {
		return nil
	}
	out := new(CloudNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CloudNamespace. Required by controller-gen.
func (in *CloudNamespace) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using KubernetesNamespace within kubernetes types, where deepcopy-gen is used.
func (in *KubernetesNamespace) DeepCopyInto(out *KubernetesNamespace) {
	p := proto.Clone(in).(*KubernetesNamespace)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesNamespace. Required by controller-gen.
func (in *KubernetesNamespace) DeepCopy() *KubernetesNamespace {
	if in == nil {
		return nil
	}
	out := new(KubernetesNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesNamespace. Required by controller-gen.
func (in *KubernetesNamespace) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
