// Antimetal API definitions
// Copyright Antimetal, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: resource/v1/object.proto

package resourcev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TypeDescriptor describes an object type.
type TypeDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The object kind full url (e.g. resource.v1.Resource,
	// resource.v1.Relationship). Kind represetnts the graph entity type. It
	// denotes whether the object is a "Resource" (graph node) or a "Relationship"
	// (graph edge).
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// The object type. This should be the full url of the protobuf type
	// of the object schema.
	Type          string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeDescriptor) Reset() {
	*x = TypeDescriptor{}
	mi := &file_resource_v1_object_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeDescriptor) ProtoMessage() {}

func (x *TypeDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_object_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeDescriptor.ProtoReflect.Descriptor instead.
func (*TypeDescriptor) Descriptor() ([]byte, []int) {
	return file_resource_v1_object_proto_rawDescGZIP(), []int{0}
}

func (x *TypeDescriptor) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TypeDescriptor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Object is a resource or relationship object.
type Object struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Describes the object type.
	Type *TypeDescriptor `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// The Resource or Relationship object
	Object *anypb.Any `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	// Time-to-live value for the object. For each object, a timer is started.
	// The timer is reset each time the object is received with a new TTL.
	// If the object is received with no TTL set, the timer is removed for the
	// object. Upon expiration of the timer, the object is considered deleted.
	//
	// The TTL can be refreshed or changed by sending a Delta containing an Object
	// with the same name that doesn't change the object version. In this case the
	// object field does not need to be populated, which allows for light-weight
	// "heartbeat" updates to keep an object with a TTL alive.
	//
	// The TTL feature is meant to support cleaning up objects in the event of
	// a systems-agent removal/failure. For example, if the Kubernetes cluster
	// where the systems agent is deployed in is spun down, then all the resources
	// from the cluster will be deleted from the graph once the TTL expires.
	Ttl *durationpb.Duration `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// The delta version of the Delta change set that the object is a part of.
	// It is used to keep track of the state of individual objects. The version is
	// set and maintained by the client sending Deltas.
	//
	// NOTE: the version string should only be used for comparisions!
	// It is not guaranteed that the version string is monotonically increasing.
	DeltaVersion  string `protobuf:"bytes,4,opt,name=delta_version,json=deltaVersion,proto3" json:"delta_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_resource_v1_object_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_object_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_resource_v1_object_proto_rawDescGZIP(), []int{1}
}

func (x *Object) GetType() *TypeDescriptor {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Object) GetObject() *anypb.Any {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *Object) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *Object) GetDeltaVersion() string {
	if x != nil {
		return x.DeltaVersion
	}
	return ""
}

var File_resource_v1_object_proto protoreflect.FileDescriptor

var file_resource_v1_object_proto_rawDesc = string([]byte{
	0x0a, 0x18, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x38, 0x0a, 0x0e, 0x54, 0x79, 0x70, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xb9, 0x01, 0x0a,
	0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x2f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x6f, 0x72, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x06,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x2b, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03,
	0x74, 0x74, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x5f, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x6c, 0x74,
	0x61, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0xa3, 0x01, 0x0a, 0x0f, 0x63, 0x6f, 0x6d,
	0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x0b, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x36, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x61,
	0x6c, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x67, 0x65, 0x6e, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x52, 0x58, 0x58, 0xaa, 0x02, 0x0b, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0b, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x17, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_resource_v1_object_proto_rawDescOnce sync.Once
	file_resource_v1_object_proto_rawDescData []byte
)

func file_resource_v1_object_proto_rawDescGZIP() []byte {
	file_resource_v1_object_proto_rawDescOnce.Do(func() {
		file_resource_v1_object_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_v1_object_proto_rawDesc), len(file_resource_v1_object_proto_rawDesc)))
	})
	return file_resource_v1_object_proto_rawDescData
}

var file_resource_v1_object_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resource_v1_object_proto_goTypes = []any{
	(*TypeDescriptor)(nil),      // 0: resource.v1.TypeDescriptor
	(*Object)(nil),              // 1: resource.v1.Object
	(*anypb.Any)(nil),           // 2: google.protobuf.Any
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
}
var file_resource_v1_object_proto_depIdxs = []int32{
	0, // 0: resource.v1.Object.type:type_name -> resource.v1.TypeDescriptor
	2, // 1: resource.v1.Object.object:type_name -> google.protobuf.Any
	3, // 2: resource.v1.Object.ttl:type_name -> google.protobuf.Duration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_resource_v1_object_proto_init() }
func file_resource_v1_object_proto_init() {
	if File_resource_v1_object_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_v1_object_proto_rawDesc), len(file_resource_v1_object_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_v1_object_proto_goTypes,
		DependencyIndexes: file_resource_v1_object_proto_depIdxs,
		MessageInfos:      file_resource_v1_object_proto_msgTypes,
	}.Build()
	File_resource_v1_object_proto = out.File
	file_resource_v1_object_proto_goTypes = nil
	file_resource_v1_object_proto_depIdxs = nil
}
