// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package resourcev1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using TypeDescriptor within kubernetes types, where deepcopy-gen is used.
func (in *TypeDescriptor) DeepCopyInto(out *TypeDescriptor) {
	p := proto.Clone(in).(*TypeDescriptor)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeDescriptor. Required by controller-gen.
func (in *TypeDescriptor) DeepCopy() *TypeDescriptor {
	if in == nil {
		return nil
	}
	out := new(TypeDescriptor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new TypeDescriptor. Required by controller-gen.
func (in *TypeDescriptor) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Object within kubernetes types, where deepcopy-gen is used.
func (in *Object) DeepCopyInto(out *Object) {
	p := proto.Clone(in).(*Object)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Object. Required by controller-gen.
func (in *Object) DeepCopy() *Object {
	if in == nil {
		return nil
	}
	out := new(Object)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Object. Required by controller-gen.
func (in *Object) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
