// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package resourcev1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using ProviderAccount within kubernetes types, where deepcopy-gen is used.
func (in *ProviderAccount) DeepCopyInto(out *ProviderAccount) {
	p := proto.Clone(in).(*ProviderAccount)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAccount. Required by controller-gen.
func (in *ProviderAccount) DeepCopy() *ProviderAccount {
	if in == nil {
		return nil
	}
	out := new(ProviderAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAccount. Required by controller-gen.
func (in *ProviderAccount) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
