// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package resourcev1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Relationship within kubernetes types, where deepcopy-gen is used.
func (in *Relationship) DeepCopyInto(out *Relationship) {
	p := proto.Clone(in).(*Relationship)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Relationship. Required by controller-gen.
func (in *Relationship) DeepCopy() *Relationship {
	if in == nil {
		return nil
	}
	out := new(Relationship)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Relationship. Required by controller-gen.
func (in *Relationship) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
