// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package resourcev1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using ResourceDescriptor within kubernetes types, where deepcopy-gen is used.
func (in *ResourceDescriptor) DeepCopyInto(out *ResourceDescriptor) {
	p := proto.Clone(in).(*ResourceDescriptor)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceDescriptor. Required by controller-gen.
func (in *ResourceDescriptor) DeepCopy() *ResourceDescriptor {
	if in == nil {
		return nil
	}
	out := new(ResourceDescriptor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ResourceDescriptor. Required by controller-gen.
func (in *ResourceDescriptor) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ResourceMeta within kubernetes types, where deepcopy-gen is used.
func (in *ResourceMeta) DeepCopyInto(out *ResourceMeta) {
	p := proto.Clone(in).(*ResourceMeta)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceMeta. Required by controller-gen.
func (in *ResourceMeta) DeepCopy() *ResourceMeta {
	if in == nil {
		return nil
	}
	out := new(ResourceMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ResourceMeta. Required by controller-gen.
func (in *ResourceMeta) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Tag within kubernetes types, where deepcopy-gen is used.
func (in *Tag) DeepCopyInto(out *Tag) {
	p := proto.Clone(in).(*Tag)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag. Required by controller-gen.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Tag. Required by controller-gen.
func (in *Tag) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Resource within kubernetes types, where deepcopy-gen is used.
func (in *Resource) DeepCopyInto(out *Resource) {
	p := proto.Clone(in).(*Resource)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resource. Required by controller-gen.
func (in *Resource) DeepCopy() *Resource {
	if in == nil {
		return nil
	}
	out := new(Resource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Resource. Required by controller-gen.
func (in *Resource) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
