// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package networkv1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using RoutesTo within kubernetes types, where deepcopy-gen is used.
func (in *RoutesTo) DeepCopyInto(out *RoutesTo) {
	p := proto.Clone(in).(*RoutesTo)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutesTo. Required by controller-gen.
func (in *RoutesTo) DeepCopy() *RoutesTo {
	if in == nil {
		return nil
	}
	out := new(RoutesTo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RoutesTo. Required by controller-gen.
func (in *RoutesTo) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using RoutedFrom within kubernetes types, where deepcopy-gen is used.
func (in *RoutedFrom) DeepCopyInto(out *RoutedFrom) {
	p := proto.Clone(in).(*RoutedFrom)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutedFrom. Required by controller-gen.
func (in *RoutedFrom) DeepCopy() *RoutedFrom {
	if in == nil {
		return nil
	}
	out := new(RoutedFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RoutedFrom. Required by controller-gen.
func (in *RoutedFrom) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
