// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package resourcev1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using DeltaRequest within kubernetes types, where deepcopy-gen is used.
func (in *DeltaRequest) DeepCopyInto(out *DeltaRequest) {
	p := proto.Clone(in).(*DeltaRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeltaRequest. Required by controller-gen.
func (in *DeltaRequest) DeepCopy() *DeltaRequest {
	if in == nil {
		return nil
	}
	out := new(DeltaRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeltaRequest. Required by controller-gen.
func (in *DeltaRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeltaResponse within kubernetes types, where deepcopy-gen is used.
func (in *DeltaResponse) DeepCopyInto(out *DeltaResponse) {
	p := proto.Clone(in).(*DeltaResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeltaResponse. Required by controller-gen.
func (in *DeltaResponse) DeepCopy() *DeltaResponse {
	if in == nil {
		return nil
	}
	out := new(DeltaResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeltaResponse. Required by controller-gen.
func (in *DeltaResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Delta within kubernetes types, where deepcopy-gen is used.
func (in *Delta) DeepCopyInto(out *Delta) {
	p := proto.Clone(in).(*Delta)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Delta. Required by controller-gen.
func (in *Delta) DeepCopy() *Delta {
	if in == nil {
		return nil
	}
	out := new(Delta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Delta. Required by controller-gen.
func (in *Delta) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
