// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package kubernetesv1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Cluster within kubernetes types, where deepcopy-gen is used.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	p := proto.Clone(in).(*Cluster)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster. Required by controller-gen.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Cluster. Required by controller-gen.
func (in *Cluster) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
