// Antimetal API definitions
// Copyright Antimetal, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: kubernetes/v1/relationships.proto

package kubernetesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Source owns the target resource (e.g. ReplicaSet "owns" Pod).
// Inverse of OwnedBy.
type Owns struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Owns) Reset() {
	*x = Owns{}
	mi := &file_kubernetes_v1_relationships_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Owns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Owns) ProtoMessage() {}

func (x *Owns) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_relationships_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Owns.ProtoReflect.Descriptor instead.
func (*Owns) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_relationships_proto_rawDescGZIP(), []int{0}
}

// Identifies the owner of a resource.
// Inverse of Owns.
type OwnedBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnedBy) Reset() {
	*x = OwnedBy{}
	mi := &file_kubernetes_v1_relationships_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnedBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedBy) ProtoMessage() {}

func (x *OwnedBy) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_relationships_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedBy.ProtoReflect.Descriptor instead.
func (*OwnedBy) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_relationships_proto_rawDescGZIP(), []int{1}
}

// Represents a volume attachment
// Inverse of AttachedTo.
type VolumeMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMount) Reset() {
	*x = VolumeMount{}
	mi := &file_kubernetes_v1_relationships_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMount) ProtoMessage() {}

func (x *VolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_relationships_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMount.ProtoReflect.Descriptor instead.
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_relationships_proto_rawDescGZIP(), []int{2}
}

// Represents the the resource that is mounting the Volume.
// Inverse of VolumeMount.
type AttachedTo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachedTo) Reset() {
	*x = AttachedTo{}
	mi := &file_kubernetes_v1_relationships_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachedTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachedTo) ProtoMessage() {}

func (x *AttachedTo) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_relationships_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachedTo.ProtoReflect.Descriptor instead.
func (*AttachedTo) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_relationships_proto_rawDescGZIP(), []int{3}
}

// Represents a resource that is a member of a group (e.g. Namespace "contains" Deployment).
// Inverse of ContainedBy.
type Contains struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contains) Reset() {
	*x = Contains{}
	mi := &file_kubernetes_v1_relationships_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contains) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contains) ProtoMessage() {}

func (x *Contains) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_relationships_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contains.ProtoReflect.Descriptor instead.
func (*Contains) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_relationships_proto_rawDescGZIP(), []int{4}
}

// Inverse of Contains. Represents the group that a resource is a member of.
type ContainedBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainedBy) Reset() {
	*x = ContainedBy{}
	mi := &file_kubernetes_v1_relationships_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainedBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainedBy) ProtoMessage() {}

func (x *ContainedBy) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_relationships_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainedBy.ProtoReflect.Descriptor instead.
func (*ContainedBy) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_relationships_proto_rawDescGZIP(), []int{5}
}

// Used to identify the persistent volume claims bound to a persistent volume.
// Inverse of ClaimsFrom.
type BoundBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundBy) Reset() {
	*x = BoundBy{}
	mi := &file_kubernetes_v1_relationships_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundBy) ProtoMessage() {}

func (x *BoundBy) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_relationships_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundBy.ProtoReflect.Descriptor instead.
func (*BoundBy) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_relationships_proto_rawDescGZIP(), []int{6}
}

// Used to identify the persistent volume that a persistent volume claim is bound to.
// Inverse of BoundBy.
type ClaimsFrom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimsFrom) Reset() {
	*x = ClaimsFrom{}
	mi := &file_kubernetes_v1_relationships_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimsFrom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimsFrom) ProtoMessage() {}

func (x *ClaimsFrom) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_relationships_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimsFrom.ProtoReflect.Descriptor instead.
func (*ClaimsFrom) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_relationships_proto_rawDescGZIP(), []int{7}
}

var File_kubernetes_v1_relationships_proto protoreflect.FileDescriptor

var file_kubernetes_v1_relationships_proto_rawDesc = string([]byte{
	0x0a, 0x21, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x2e,
	0x76, 0x31, 0x22, 0x06, 0x0a, 0x04, 0x4f, 0x77, 0x6e, 0x73, 0x22, 0x09, 0x0a, 0x07, 0x4f, 0x77,
	0x6e, 0x65, 0x64, 0x42, 0x79, 0x22, 0x0d, 0x0a, 0x0b, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4d,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x0c, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64,
	0x54, 0x6f, 0x22, 0x0a, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x22, 0x0d,
	0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x42, 0x79, 0x22, 0x09, 0x0a,
	0x07, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x42, 0x79, 0x22, 0x0c, 0x0a, 0x0a, 0x43, 0x6c, 0x61, 0x69,
	0x6d, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x42, 0xb8, 0x01, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x6b,
	0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x42, 0x12, 0x52, 0x65,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x67, 0x65,
	0x6e, 0x67, 0x6f, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x2f, 0x76,
	0x31, 0x3b, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x76, 0x31, 0xa2, 0x02,
	0x03, 0x4b, 0x58, 0x58, 0xaa, 0x02, 0x0d, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65,
	0x73, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0d, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65,
	0x73, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x19, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65,
	0x73, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x0e, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x3a, 0x3a, 0x56,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_kubernetes_v1_relationships_proto_rawDescOnce sync.Once
	file_kubernetes_v1_relationships_proto_rawDescData []byte
)

func file_kubernetes_v1_relationships_proto_rawDescGZIP() []byte {
	file_kubernetes_v1_relationships_proto_rawDescOnce.Do(func() {
		file_kubernetes_v1_relationships_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubernetes_v1_relationships_proto_rawDesc), len(file_kubernetes_v1_relationships_proto_rawDesc)))
	})
	return file_kubernetes_v1_relationships_proto_rawDescData
}

var file_kubernetes_v1_relationships_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kubernetes_v1_relationships_proto_goTypes = []any{
	(*Owns)(nil),        // 0: kubernetes.v1.Owns
	(*OwnedBy)(nil),     // 1: kubernetes.v1.OwnedBy
	(*VolumeMount)(nil), // 2: kubernetes.v1.VolumeMount
	(*AttachedTo)(nil),  // 3: kubernetes.v1.AttachedTo
	(*Contains)(nil),    // 4: kubernetes.v1.Contains
	(*ContainedBy)(nil), // 5: kubernetes.v1.ContainedBy
	(*BoundBy)(nil),     // 6: kubernetes.v1.BoundBy
	(*ClaimsFrom)(nil),  // 7: kubernetes.v1.ClaimsFrom
}
var file_kubernetes_v1_relationships_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kubernetes_v1_relationships_proto_init() }
func file_kubernetes_v1_relationships_proto_init() {
	if File_kubernetes_v1_relationships_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubernetes_v1_relationships_proto_rawDesc), len(file_kubernetes_v1_relationships_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubernetes_v1_relationships_proto_goTypes,
		DependencyIndexes: file_kubernetes_v1_relationships_proto_depIdxs,
		MessageInfos:      file_kubernetes_v1_relationships_proto_msgTypes,
	}.Build()
	File_kubernetes_v1_relationships_proto = out.File
	file_kubernetes_v1_relationships_proto_goTypes = nil
	file_kubernetes_v1_relationships_proto_depIdxs = nil
}
