// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package kubernetesv1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Owns within kubernetes types, where deepcopy-gen is used.
func (in *Owns) DeepCopyInto(out *Owns) {
	p := proto.Clone(in).(*Owns)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Owns. Required by controller-gen.
func (in *Owns) DeepCopy() *Owns {
	if in == nil {
		return nil
	}
	out := new(Owns)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Owns. Required by controller-gen.
func (in *Owns) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using OwnedBy within kubernetes types, where deepcopy-gen is used.
func (in *OwnedBy) DeepCopyInto(out *OwnedBy) {
	p := proto.Clone(in).(*OwnedBy)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnedBy. Required by controller-gen.
func (in *OwnedBy) DeepCopy() *OwnedBy {
	if in == nil {
		return nil
	}
	out := new(OwnedBy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new OwnedBy. Required by controller-gen.
func (in *OwnedBy) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using VolumeMount within kubernetes types, where deepcopy-gen is used.
func (in *VolumeMount) DeepCopyInto(out *VolumeMount) {
	p := proto.Clone(in).(*VolumeMount)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeMount. Required by controller-gen.
func (in *VolumeMount) DeepCopy() *VolumeMount {
	if in == nil {
		return nil
	}
	out := new(VolumeMount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VolumeMount. Required by controller-gen.
func (in *VolumeMount) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AttachedTo within kubernetes types, where deepcopy-gen is used.
func (in *AttachedTo) DeepCopyInto(out *AttachedTo) {
	p := proto.Clone(in).(*AttachedTo)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttachedTo. Required by controller-gen.
func (in *AttachedTo) DeepCopy() *AttachedTo {
	if in == nil {
		return nil
	}
	out := new(AttachedTo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AttachedTo. Required by controller-gen.
func (in *AttachedTo) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Contains within kubernetes types, where deepcopy-gen is used.
func (in *Contains) DeepCopyInto(out *Contains) {
	p := proto.Clone(in).(*Contains)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Contains. Required by controller-gen.
func (in *Contains) DeepCopy() *Contains {
	if in == nil {
		return nil
	}
	out := new(Contains)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Contains. Required by controller-gen.
func (in *Contains) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ContainedBy within kubernetes types, where deepcopy-gen is used.
func (in *ContainedBy) DeepCopyInto(out *ContainedBy) {
	p := proto.Clone(in).(*ContainedBy)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainedBy. Required by controller-gen.
func (in *ContainedBy) DeepCopy() *ContainedBy {
	if in == nil {
		return nil
	}
	out := new(ContainedBy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ContainedBy. Required by controller-gen.
func (in *ContainedBy) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using BoundBy within kubernetes types, where deepcopy-gen is used.
func (in *BoundBy) DeepCopyInto(out *BoundBy) {
	p := proto.Clone(in).(*BoundBy)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoundBy. Required by controller-gen.
func (in *BoundBy) DeepCopy() *BoundBy {
	if in == nil {
		return nil
	}
	out := new(BoundBy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new BoundBy. Required by controller-gen.
func (in *BoundBy) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ClaimsFrom within kubernetes types, where deepcopy-gen is used.
func (in *ClaimsFrom) DeepCopyInto(out *ClaimsFrom) {
	p := proto.Clone(in).(*ClaimsFrom)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClaimsFrom. Required by controller-gen.
func (in *ClaimsFrom) DeepCopy() *ClaimsFrom {
	if in == nil {
		return nil
	}
	out := new(ClaimsFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ClaimsFrom. Required by controller-gen.
func (in *ClaimsFrom) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
