// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package kubernetesv1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Cluster within kubernetes types, where deepcopy-gen is used.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	p := proto.Clone(in).(*Cluster)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster. Required by controller-gen.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Cluster. Required by controller-gen.
func (in *Cluster) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using EKS within kubernetes types, where deepcopy-gen is used.
func (in *EKS) DeepCopyInto(out *EKS) {
	p := proto.Clone(in).(*EKS)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EKS. Required by controller-gen.
func (in *EKS) DeepCopy() *EKS {
	if in == nil {
		return nil
	}
	out := new(EKS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new EKS. Required by controller-gen.
func (in *EKS) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GKE within kubernetes types, where deepcopy-gen is used.
func (in *GKE) DeepCopyInto(out *GKE) {
	p := proto.Clone(in).(*GKE)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKE. Required by controller-gen.
func (in *GKE) DeepCopy() *GKE {
	if in == nil {
		return nil
	}
	out := new(GKE)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GKE. Required by controller-gen.
func (in *GKE) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AKS within kubernetes types, where deepcopy-gen is used.
func (in *AKS) DeepCopyInto(out *AKS) {
	p := proto.Clone(in).(*AKS)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AKS. Required by controller-gen.
func (in *AKS) DeepCopy() *AKS {
	if in == nil {
		return nil
	}
	out := new(AKS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AKS. Required by controller-gen.
func (in *AKS) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Kind within kubernetes types, where deepcopy-gen is used.
func (in *Kind) DeepCopyInto(out *Kind) {
	p := proto.Clone(in).(*Kind)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kind. Required by controller-gen.
func (in *Kind) DeepCopy() *Kind {
	if in == nil {
		return nil
	}
	out := new(Kind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Kind. Required by controller-gen.
func (in *Kind) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
